frontend:
  baseurl: http://localhost:5173

application:
  uploads:
    path: uploads

spring:
  profiles:
    active: dev
  application:
    name: learnhub-api
    security:
      jwt:
        expiration: 300000 # 5 minutes
        refresh-token:
          expiration: 86400000 # 1 day
  main:
    banner-mode: off
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: learnhub391@gmail.com
    password: rivu yxgn hqkz uepl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    root: error
