frontend:
  baseurl: http://localhost:5173

spring:
  application:
    name: learnhub-api
    security:
      jwt:
        expiration: 900000 # 15 minutes
        refresh-token:
          expiration: 86400000 # 1 day
  main:
    banner-mode: off
  datasource:
    url: jdbc:mysql://localhost:3306/learnhub
    username: sa
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: learnhub391@gmail.com
    password: rivu yxgn hqkz uepl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


logging:
  level:
    root: warn