frontend:
  baseurl: http://localhost:8080

spring:
  application:
    name: learnhub-api
    security:
      jwt:
        expiration: 900000
  datasource:
    url: jdbc:mysql://localhost:3306/learnhub
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: learnhub391@gmail.com
    password: rivu yxgn hqkz uepl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
